USE [master]
GO

/****** Object:  Database [myProject]    Script Date: 28/11/2014 17:33:13 ******/
CREATE DATABASE [myProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'myProject', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\myProject.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'myProject_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\myProject_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [myProject] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [myProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [myProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [myProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [myProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [myProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [myProject] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [myProject] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [myProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [myProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [myProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [myProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [myProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [myProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [myProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [myProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [myProject] SET  ENABLE_BROKER 
GO

ALTER DATABASE [myProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [myProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [myProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [myProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [myProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [myProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [myProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [myProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [myProject] SET  MULTI_USER 
GO

ALTER DATABASE [myProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [myProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [myProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [myProject] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [myProject] SET  READ_WRITE 
GO


