//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmentModule
    {
        public tblDepartmentModule()
        {
            this.tblLectures = new HashSet<tblLecture>();
            this.tblProfessorModules = new HashSet<tblProfessorModule>();
            this.tblStudentModules = new HashSet<tblStudentModule>();
        }
    
        public int PK_Module_id { get; set; }
        public string module_name { get; set; }
        public Nullable<int> FK_Department_id { get; set; }
        public string module_code { get; set; }
        public string term { get; set; }
    
        public virtual tblUniversityDepartment tblUniversityDepartment { get; set; }
        public virtual ICollection<tblLecture> tblLectures { get; set; }
        public virtual ICollection<tblProfessorModule> tblProfessorModules { get; set; }
        public virtual ICollection<tblStudentModule> tblStudentModules { get; set; }
    }
}
