//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedbackResult
    {
        public int PK_Feedback_result_id { get; set; }
        public Nullable<int> FK_Feedback_id { get; set; }
        public Nullable<int> FK_Student_id { get; set; }
        public Nullable<float> feedback_answer { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }
    
        public virtual tblFeedback tblFeedback { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
