//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public tblFeedback()
        {
            this.tblFeedbackResults = new HashSet<tblFeedbackResult>();
        }
    
        public int PK_Feedback_id { get; set; }
        public Nullable<int> FK_Lecture_id { get; set; }
        public Nullable<float> feedback_value { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual ICollection<tblFeedbackResult> tblFeedbackResults { get; set; }
        public virtual tblLecture tblLecture { get; set; }
    }
}
