//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLecture
    {
        public tblLecture()
        {
            this.tblFeedbacks = new HashSet<tblFeedback>();
        }
    
        public int PK_Lecture_id { get; set; }
        public Nullable<int> FK_Module_id { get; set; }
        public Nullable<int> FK_Professor_id { get; set; }
        public string lecture_title { get; set; }
        public Nullable<System.DateTime> lecture_date { get; set; }
        public Nullable<System.TimeSpan> lecture_time { get; set; }
        public Nullable<int> lecture_status { get; set; }
    
        public virtual tblDepartmentModule tblDepartmentModule { get; set; }
        public virtual ICollection<tblFeedback> tblFeedbacks { get; set; }
        public virtual tblProfessor tblProfessor { get; set; }
    }
}
