//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfessorLogin
    {
        public int PK_Professor_login_id { get; set; }
        public int FK_Professor_id { get; set; }
        public string email { get; set; }
        public string pass_value { get; set; }
        public Nullable<System.DateTime> lastLogindate { get; set; }
        public Nullable<int> isLogin { get; set; }
        public string session_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual tblProfessor tblProfessor { get; set; }
    }
}
