//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfessor
    {
        public tblProfessor()
        {
            this.tblLectures = new HashSet<tblLecture>();
            this.tblProfessorLogins = new HashSet<tblProfessorLogin>();
            this.tblProfessorModules = new HashSet<tblProfessorModule>();
            this.tblQuizDetails = new HashSet<tblQuizDetail>();
        }
    
        public int PK_Professor_id { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string profile_pic { get; set; }
        public Nullable<int> FK_University_id { get; set; }
        public string department_name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string pass_value { get; set; }
        public string verification_code { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<tblLecture> tblLectures { get; set; }
        public virtual ICollection<tblProfessorLogin> tblProfessorLogins { get; set; }
        public virtual ICollection<tblProfessorModule> tblProfessorModules { get; set; }
        public virtual tblUniversity tblUniversity { get; set; }
        public virtual ICollection<tblQuizDetail> tblQuizDetails { get; set; }
    }
}
