//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuizOption
    {
        public tblQuizOption()
        {
            this.tblQuizResults = new HashSet<tblQuizResult>();
        }
    
        public int PK_Option_id { get; set; }
        public int FK_Question_id { get; set; }
        public string option_value { get; set; }
        public Nullable<int> isAnswer { get; set; }
    
        public virtual tblQuizQuestion tblQuizQuestion { get; set; }
        public virtual ICollection<tblQuizResult> tblQuizResults { get; set; }
    }
}
