//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuizDetail
    {
        public tblQuizDetail()
        {
            this.tblQuizQuestions = new HashSet<tblQuizQuestion>();
            this.tblQuizResults = new HashSet<tblQuizResult>();
        }
    
        public int PK_Quiz_id { get; set; }
        public int FK_Professor_id { get; set; }
        public string quiz_title { get; set; }
        public Nullable<System.DateTime> quiz_date { get; set; }
        public Nullable<int> isTimeup { get; set; }
        public Nullable<float> quiz_length { get; set; }
        public Nullable<float> quiz_weightage { get; set; }
        public Nullable<int> quiz_status { get; set; }
        public Nullable<System.DateTime> quiz_end_date { get; set; }
        public Nullable<System.DateTime> quiz_update { get; set; }
        public int FK_ModuleId { get; set; }
    
        public virtual tblProfessor tblProfessor { get; set; }
        public virtual ICollection<tblQuizQuestion> tblQuizQuestions { get; set; }
        public virtual ICollection<tblQuizResult> tblQuizResults { get; set; }
    }
}
