//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuizResult
    {
        public int PK_QuestionResult_Id { get; set; }
        public Nullable<int> FK_QuizId { get; set; }
        public Nullable<int> FK_QuestionId { get; set; }
        public Nullable<int> FK_OptionId { get; set; }
        public Nullable<int> FK_studentId { get; set; }
        public Nullable<double> marks { get; set; }
        public Nullable<int> isAnswered { get; set; }
        public Nullable<System.DateTime> update { get; set; }
        public string answer { get; set; }
    
        public virtual tblQuizDetail tblQuizDetail { get; set; }
        public virtual tblQuizOption tblQuizOption { get; set; }
        public virtual tblQuizQuestion tblQuizQuestion { get; set; }
    }
}
