//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniversity
    {
        public tblUniversity()
        {
            this.tblProfessors = new HashSet<tblProfessor>();
            this.tblStudents = new HashSet<tblStudent>();
            this.tblUniversityDepartments = new HashSet<tblUniversityDepartment>();
        }
    
        public int PK_University_id { get; set; }
        public string university_name { get; set; }
    
        public virtual ICollection<tblProfessor> tblProfessors { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblUniversityDepartment> tblUniversityDepartments { get; set; }
    }
}
