//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWCFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniversityDepartment
    {
        public tblUniversityDepartment()
        {
            this.tblDepartmentModules = new HashSet<tblDepartmentModule>();
        }
    
        public int PK_Department_id { get; set; }
        public Nullable<int> FK_University_id { get; set; }
        public string department_name { get; set; }
    
        public virtual ICollection<tblDepartmentModule> tblDepartmentModules { get; set; }
        public virtual tblUniversity tblUniversity { get; set; }
    }
}
