//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAspClient.student_WCFLib {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentProfile", Namespace="http://schemas.datacontract.org/2004/07/myWCFClassLibrary")]
    [System.SerializableAttribute()]
    public partial class StudentProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FK_University_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PK_Student_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string course_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string department_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middlenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass_valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profile_picField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> semesterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string verification_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FK_University_id {
            get {
                return this.FK_University_idField;
            }
            set {
                if ((this.FK_University_idField.Equals(value) != true)) {
                    this.FK_University_idField = value;
                    this.RaisePropertyChanged("FK_University_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PK_Student_id {
            get {
                return this.PK_Student_idField;
            }
            set {
                if ((this.PK_Student_idField.Equals(value) != true)) {
                    this.PK_Student_idField = value;
                    this.RaisePropertyChanged("PK_Student_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string course_name {
            get {
                return this.course_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.course_nameField, value) != true)) {
                    this.course_nameField = value;
                    this.RaisePropertyChanged("course_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department_name {
            get {
                return this.department_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.department_nameField, value) != true)) {
                    this.department_nameField = value;
                    this.RaisePropertyChanged("department_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                if ((object.ReferenceEquals(this.middlenameField, value) != true)) {
                    this.middlenameField = value;
                    this.RaisePropertyChanged("middlename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_value {
            get {
                return this.pass_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.pass_valueField, value) != true)) {
                    this.pass_valueField = value;
                    this.RaisePropertyChanged("pass_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profile_pic {
            get {
                return this.profile_picField;
            }
            set {
                if ((object.ReferenceEquals(this.profile_picField, value) != true)) {
                    this.profile_picField = value;
                    this.RaisePropertyChanged("profile_pic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> semester {
            get {
                return this.semesterField;
            }
            set {
                if ((this.semesterField.Equals(value) != true)) {
                    this.semesterField = value;
                    this.RaisePropertyChanged("semester");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string verification_code {
            get {
                return this.verification_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.verification_codeField, value) != true)) {
                    this.verification_codeField = value;
                    this.RaisePropertyChanged("verification_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="student_WCFLib.IStudentProfile")]
    public interface IStudentProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfile/CreateStudent", ReplyAction="http://tempuri.org/IStudentProfile/CreateStudentResponse")]
        string CreateStudent(myWebAspClient.student_WCFLib.StudentProfile stdntProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentProfile/CreateStudent", ReplyAction="http://tempuri.org/IStudentProfile/CreateStudentResponse")]
        System.Threading.Tasks.Task<string> CreateStudentAsync(myWebAspClient.student_WCFLib.StudentProfile stdntProfile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentProfileChannel : myWebAspClient.student_WCFLib.IStudentProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentProfileClient : System.ServiceModel.ClientBase<myWebAspClient.student_WCFLib.IStudentProfile>, myWebAspClient.student_WCFLib.IStudentProfile {
        
        public StudentProfileClient() {
        }
        
        public StudentProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateStudent(myWebAspClient.student_WCFLib.StudentProfile stdntProfile) {
            return base.Channel.CreateStudent(stdntProfile);
        }
        
        public System.Threading.Tasks.Task<string> CreateStudentAsync(myWebAspClient.student_WCFLib.StudentProfile stdntProfile) {
            return base.Channel.CreateStudentAsync(stdntProfile);
        }
    }
}
