//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAspClient.professor_Report_WCFLib {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="professor_Report_WCFLib.IProfessorReport")]
    public interface IProfessorReport {
        
        // CODEGEN: Parameter 'getAllQuizByModuleResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllQuizByModule", ReplyAction="http://tempuri.org/IProfessorReport/getAllQuizByModuleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleResponse getAllQuizByModule(myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllQuizByModule", ReplyAction="http://tempuri.org/IProfessorReport/getAllQuizByModuleResponse")]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleResponse> getAllQuizByModuleAsync(myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest request);
        
        // CODEGEN: Parameter 'getAllModuleByTermResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllModuleByTerm", ReplyAction="http://tempuri.org/IProfessorReport/getAllModuleByTermResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        myWebAspClient.professor_Report_WCFLib.getAllModuleByTermResponse getAllModuleByTerm(myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllModuleByTerm", ReplyAction="http://tempuri.org/IProfessorReport/getAllModuleByTermResponse")]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllModuleByTermResponse> getAllModuleByTermAsync(myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest request);
        
        // CODEGEN: Parameter 'getAllQuestionsByQuizResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllQuestionsByQuiz", ReplyAction="http://tempuri.org/IProfessorReport/getAllQuestionsByQuizResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizResponse getAllQuestionsByQuiz(myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllQuestionsByQuiz", ReplyAction="http://tempuri.org/IProfessorReport/getAllQuestionsByQuizResponse")]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizResponse> getAllQuestionsByQuizAsync(myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest request);
        
        // CODEGEN: Parameter 'getStatusByQuestionIdResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getStatusByQuestionId", ReplyAction="http://tempuri.org/IProfessorReport/getStatusByQuestionIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdResponse getStatusByQuestionId(myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getStatusByQuestionId", ReplyAction="http://tempuri.org/IProfessorReport/getStatusByQuestionIdResponse")]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdResponse> getStatusByQuestionIdAsync(myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest request);
        
        // CODEGEN: Parameter 'getAllQuizbyStudentResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllQuizbyStudent", ReplyAction="http://tempuri.org/IProfessorReport/getAllQuizbyStudentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentResponse getAllQuizbyStudent(myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllQuizbyStudent", ReplyAction="http://tempuri.org/IProfessorReport/getAllQuizbyStudentResponse")]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentResponse> getAllQuizbyStudentAsync(myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest request);
        
        // CODEGEN: Parameter 'getAllFeedbacksResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllFeedbacks", ReplyAction="http://tempuri.org/IProfessorReport/getAllFeedbacksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        myWebAspClient.professor_Report_WCFLib.getAllFeedbacksResponse getAllFeedbacks(myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorReport/getAllFeedbacks", ReplyAction="http://tempuri.org/IProfessorReport/getAllFeedbacksResponse")]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllFeedbacksResponse> getAllFeedbacksAsync(myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQuizByModule", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllQuizByModuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int moduleId;
        
        public getAllQuizByModuleRequest() {
        }
        
        public getAllQuizByModuleRequest(int moduleId) {
            this.moduleId = moduleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQuizByModuleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllQuizByModuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet getAllQuizByModuleResult;
        
        public getAllQuizByModuleResponse() {
        }
        
        public getAllQuizByModuleResponse(System.Data.DataSet getAllQuizByModuleResult) {
            this.getAllQuizByModuleResult = getAllQuizByModuleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllModuleByTerm", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllModuleByTermRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string term;
        
        public getAllModuleByTermRequest() {
        }
        
        public getAllModuleByTermRequest(string term) {
            this.term = term;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllModuleByTermResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllModuleByTermResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet getAllModuleByTermResult;
        
        public getAllModuleByTermResponse() {
        }
        
        public getAllModuleByTermResponse(System.Data.DataSet getAllModuleByTermResult) {
            this.getAllModuleByTermResult = getAllModuleByTermResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQuestionsByQuiz", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllQuestionsByQuizRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int quizId;
        
        public getAllQuestionsByQuizRequest() {
        }
        
        public getAllQuestionsByQuizRequest(int quizId) {
            this.quizId = quizId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQuestionsByQuizResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllQuestionsByQuizResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet getAllQuestionsByQuizResult;
        
        public getAllQuestionsByQuizResponse() {
        }
        
        public getAllQuestionsByQuizResponse(System.Data.DataSet getAllQuestionsByQuizResult) {
            this.getAllQuestionsByQuizResult = getAllQuestionsByQuizResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusByQuestionId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStatusByQuestionIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int questionId;
        
        public getStatusByQuestionIdRequest() {
        }
        
        public getStatusByQuestionIdRequest(int questionId) {
            this.questionId = questionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusByQuestionIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStatusByQuestionIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] getStatusByQuestionIdResult;
        
        public getStatusByQuestionIdResponse() {
        }
        
        public getStatusByQuestionIdResponse(string[] getStatusByQuestionIdResult) {
            this.getStatusByQuestionIdResult = getStatusByQuestionIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQuizbyStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllQuizbyStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int studentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int moduleId;
        
        public getAllQuizbyStudentRequest() {
        }
        
        public getAllQuizbyStudentRequest(int studentId, int moduleId) {
            this.studentId = studentId;
            this.moduleId = moduleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllQuizbyStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllQuizbyStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet getAllQuizbyStudentResult;
        
        public getAllQuizbyStudentResponse() {
        }
        
        public getAllQuizbyStudentResponse(System.Data.DataSet getAllQuizbyStudentResult) {
            this.getAllQuizbyStudentResult = getAllQuizbyStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFeedbacks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllFeedbacksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int moduleId;
        
        public getAllFeedbacksRequest() {
        }
        
        public getAllFeedbacksRequest(int moduleId) {
            this.moduleId = moduleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllFeedbacksResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllFeedbacksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet getAllFeedbacksResult;
        
        public getAllFeedbacksResponse() {
        }
        
        public getAllFeedbacksResponse(System.Data.DataSet getAllFeedbacksResult) {
            this.getAllFeedbacksResult = getAllFeedbacksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfessorReportChannel : myWebAspClient.professor_Report_WCFLib.IProfessorReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfessorReportClient : System.ServiceModel.ClientBase<myWebAspClient.professor_Report_WCFLib.IProfessorReport>, myWebAspClient.professor_Report_WCFLib.IProfessorReport {
        
        public ProfessorReportClient() {
        }
        
        public ProfessorReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfessorReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessorReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessorReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleResponse myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllQuizByModule(myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest request) {
            return base.Channel.getAllQuizByModule(request);
        }
        
        public System.Data.DataSet getAllQuizByModule(int moduleId) {
            myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest();
            inValue.moduleId = moduleId;
            myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleResponse retVal = ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllQuizByModule(inValue);
            return retVal.getAllQuizByModuleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleResponse> myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllQuizByModuleAsync(myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest request) {
            return base.Channel.getAllQuizByModuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleResponse> getAllQuizByModuleAsync(int moduleId) {
            myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllQuizByModuleRequest();
            inValue.moduleId = moduleId;
            return ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllQuizByModuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myWebAspClient.professor_Report_WCFLib.getAllModuleByTermResponse myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllModuleByTerm(myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest request) {
            return base.Channel.getAllModuleByTerm(request);
        }
        
        public System.Data.DataSet getAllModuleByTerm(string term) {
            myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest();
            inValue.term = term;
            myWebAspClient.professor_Report_WCFLib.getAllModuleByTermResponse retVal = ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllModuleByTerm(inValue);
            return retVal.getAllModuleByTermResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllModuleByTermResponse> myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllModuleByTermAsync(myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest request) {
            return base.Channel.getAllModuleByTermAsync(request);
        }
        
        public System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllModuleByTermResponse> getAllModuleByTermAsync(string term) {
            myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllModuleByTermRequest();
            inValue.term = term;
            return ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllModuleByTermAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizResponse myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllQuestionsByQuiz(myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest request) {
            return base.Channel.getAllQuestionsByQuiz(request);
        }
        
        public System.Data.DataSet getAllQuestionsByQuiz(int quizId) {
            myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest();
            inValue.quizId = quizId;
            myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizResponse retVal = ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllQuestionsByQuiz(inValue);
            return retVal.getAllQuestionsByQuizResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizResponse> myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllQuestionsByQuizAsync(myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest request) {
            return base.Channel.getAllQuestionsByQuizAsync(request);
        }
        
        public System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizResponse> getAllQuestionsByQuizAsync(int quizId) {
            myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllQuestionsByQuizRequest();
            inValue.quizId = quizId;
            return ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllQuestionsByQuizAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdResponse myWebAspClient.professor_Report_WCFLib.IProfessorReport.getStatusByQuestionId(myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest request) {
            return base.Channel.getStatusByQuestionId(request);
        }
        
        public string[] getStatusByQuestionId(int questionId) {
            myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest inValue = new myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest();
            inValue.questionId = questionId;
            myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdResponse retVal = ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getStatusByQuestionId(inValue);
            return retVal.getStatusByQuestionIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdResponse> myWebAspClient.professor_Report_WCFLib.IProfessorReport.getStatusByQuestionIdAsync(myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest request) {
            return base.Channel.getStatusByQuestionIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdResponse> getStatusByQuestionIdAsync(int questionId) {
            myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest inValue = new myWebAspClient.professor_Report_WCFLib.getStatusByQuestionIdRequest();
            inValue.questionId = questionId;
            return ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getStatusByQuestionIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentResponse myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllQuizbyStudent(myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest request) {
            return base.Channel.getAllQuizbyStudent(request);
        }
        
        public System.Data.DataSet getAllQuizbyStudent(int studentId, int moduleId) {
            myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest();
            inValue.studentId = studentId;
            inValue.moduleId = moduleId;
            myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentResponse retVal = ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllQuizbyStudent(inValue);
            return retVal.getAllQuizbyStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentResponse> myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllQuizbyStudentAsync(myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest request) {
            return base.Channel.getAllQuizbyStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentResponse> getAllQuizbyStudentAsync(int studentId, int moduleId) {
            myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllQuizbyStudentRequest();
            inValue.studentId = studentId;
            inValue.moduleId = moduleId;
            return ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllQuizbyStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        myWebAspClient.professor_Report_WCFLib.getAllFeedbacksResponse myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllFeedbacks(myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest request) {
            return base.Channel.getAllFeedbacks(request);
        }
        
        public System.Data.DataSet getAllFeedbacks(int moduleId) {
            myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest();
            inValue.moduleId = moduleId;
            myWebAspClient.professor_Report_WCFLib.getAllFeedbacksResponse retVal = ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllFeedbacks(inValue);
            return retVal.getAllFeedbacksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllFeedbacksResponse> myWebAspClient.professor_Report_WCFLib.IProfessorReport.getAllFeedbacksAsync(myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest request) {
            return base.Channel.getAllFeedbacksAsync(request);
        }
        
        public System.Threading.Tasks.Task<myWebAspClient.professor_Report_WCFLib.getAllFeedbacksResponse> getAllFeedbacksAsync(int moduleId) {
            myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest inValue = new myWebAspClient.professor_Report_WCFLib.getAllFeedbacksRequest();
            inValue.moduleId = moduleId;
            return ((myWebAspClient.professor_Report_WCFLib.IProfessorReport)(this)).getAllFeedbacksAsync(inValue);
        }
    }
}
