//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAspClient.professor_WCFLib {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Professor_Profile", Namespace="http://schemas.datacontract.org/2004/07/myWCFClassLibrary.Professor")]
    [System.SerializableAttribute()]
    public partial class Professor_Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FK_University_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PK_Professor_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string department_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middlenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass_valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profile_picField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string verification_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FK_University_id {
            get {
                return this.FK_University_idField;
            }
            set {
                if ((this.FK_University_idField.Equals(value) != true)) {
                    this.FK_University_idField = value;
                    this.RaisePropertyChanged("FK_University_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PK_Professor_id {
            get {
                return this.PK_Professor_idField;
            }
            set {
                if ((this.PK_Professor_idField.Equals(value) != true)) {
                    this.PK_Professor_idField = value;
                    this.RaisePropertyChanged("PK_Professor_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department_name {
            get {
                return this.department_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.department_nameField, value) != true)) {
                    this.department_nameField = value;
                    this.RaisePropertyChanged("department_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                if ((object.ReferenceEquals(this.middlenameField, value) != true)) {
                    this.middlenameField = value;
                    this.RaisePropertyChanged("middlename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((this.mobileField.Equals(value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_value {
            get {
                return this.pass_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.pass_valueField, value) != true)) {
                    this.pass_valueField = value;
                    this.RaisePropertyChanged("pass_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profile_pic {
            get {
                return this.profile_picField;
            }
            set {
                if ((object.ReferenceEquals(this.profile_picField, value) != true)) {
                    this.profile_picField = value;
                    this.RaisePropertyChanged("profile_pic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string verification_code {
            get {
                return this.verification_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.verification_codeField, value) != true)) {
                    this.verification_codeField = value;
                    this.RaisePropertyChanged("verification_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="professor_WCFLib.IProfessorProfile")]
    public interface IProfessorProfile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorProfile/CreateProfessor", ReplyAction="http://tempuri.org/IProfessorProfile/CreateProfessorResponse")]
        string CreateProfessor(myWebAspClient.professor_WCFLib.Professor_Profile professorProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorProfile/CreateProfessor", ReplyAction="http://tempuri.org/IProfessorProfile/CreateProfessorResponse")]
        System.Threading.Tasks.Task<string> CreateProfessorAsync(myWebAspClient.professor_WCFLib.Professor_Profile professorProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorProfile/Dashboard", ReplyAction="http://tempuri.org/IProfessorProfile/DashboardResponse")]
        int[] Dashboard(int ProfId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorProfile/Dashboard", ReplyAction="http://tempuri.org/IProfessorProfile/DashboardResponse")]
        System.Threading.Tasks.Task<int[]> DashboardAsync(int ProfId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfessorProfileChannel : myWebAspClient.professor_WCFLib.IProfessorProfile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfessorProfileClient : System.ServiceModel.ClientBase<myWebAspClient.professor_WCFLib.IProfessorProfile>, myWebAspClient.professor_WCFLib.IProfessorProfile {
        
        public ProfessorProfileClient() {
        }
        
        public ProfessorProfileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfessorProfileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessorProfileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessorProfileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateProfessor(myWebAspClient.professor_WCFLib.Professor_Profile professorProfile) {
            return base.Channel.CreateProfessor(professorProfile);
        }
        
        public System.Threading.Tasks.Task<string> CreateProfessorAsync(myWebAspClient.professor_WCFLib.Professor_Profile professorProfile) {
            return base.Channel.CreateProfessorAsync(professorProfile);
        }
        
        public int[] Dashboard(int ProfId) {
            return base.Channel.Dashboard(ProfId);
        }
        
        public System.Threading.Tasks.Task<int[]> DashboardAsync(int ProfId) {
            return base.Channel.DashboardAsync(ProfId);
        }
    }
}
